// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1iK3n5YF2XBCh2qUty-ijGmGwusaMYE',
    appId: '1:1048487312933:android:4ed6b033f60730efbf89cc',
    messagingSenderId: '1048487312933',
    projectId: 'maestros-master',
    storageBucket: 'maestros-master.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgww40KyZHxNmTKuxqizhL2Ope13jqCKs',
    appId: '1:1048487312933:web:916a0547b0c5f547bf89cc',
    messagingSenderId: '1048487312933',
    projectId: 'maestros-master',
    authDomain: 'maestros-master.firebaseapp.com',
    storageBucket: 'maestros-master.appspot.com',
    measurementId: 'G-VZYM2TGFQH',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgww40KyZHxNmTKuxqizhL2Ope13jqCKs',
    appId: '1:1048487312933:web:b20a362a815a6fbdbf89cc',
    messagingSenderId: '1048487312933',
    projectId: 'maestros-master',
    authDomain: 'maestros-master.firebaseapp.com',
    storageBucket: 'maestros-master.appspot.com',
    measurementId: 'G-6GYZD5X6S9',
  );

}